import { ROUTES } from '@/utils/routes'
import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Syndrome Main Computer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Link href={ROUTES.AUTHENTICATION}>Go to authentication</Link>
    </>
  )
}
